### ISSUE TITLE
Not working on CLion 1.0.2

### ISSUE THREAD

**Issue by alexandrezia** [rover12421/JetbrainsPatchKeygen#10]

**Comment by rover12421** [comment]
more info?

**Comment by rover12421** [comment]
1.After the update has  re-patch?
2.Is patched or run clion? You had tried to restart clion

**Comment by alexandrezia** [comment]
After update to 1.0.2 and restart, CLion complains about corrupted license, 
Re-patch and Restart, same complaint (corrupted license)

**Comment by rover12421** [comment]
Re-patch, don't run clion, try  again

**Comment by Negan1911** [comment]
Works great, thank you. What about Resharper ultimate?

**Comment by alexandrezia** [comment]
worked, thanks!
