### ISSUE TITLE
新版CLION不适用

### ISSUE THREAD

**Issue by zhangciwu** [rover12421/JetbrainsPatchKeygen#5]
RT
（新版指的是1.0.1）

**Comment by rover12421** [comment]
请确定是否打过补丁.
升级安装之后,需要重新打补丁,打完补丁可以继续使用原来已经注册的信息.

**Comment by zhangciwu** [comment]
打不上，选择.app的文件夹，还是clion.jar的文件夹，还是clion.jar
都说找不到文件

**Comment by rover12421** [comment]
有异常信息吗?
是不是权限不够?可以尝试把`clion.jar`复制出来,打了补丁再覆盖过去.

**Comment by zhangciwu** [comment]
Clion need patch
Please enter your Clion install path or clion.jar path :
/Applications/CLion.app/Contents/lib/clion.jar 
Err : Not found clion.jar.
Clion install path or clion.jar path error!
Please re-enter!

**Comment by rover12421** [comment]
从错误来看,确实是java里判断这个clion.jar不存在,这个时候还没去打补丁.
你确定下这个文件位置是不正确的.在命令行用`ls /Applications/CLion.app/Contents/lib/clion.jar `查看下

**Comment by zhangciwu** [comment]
不会有问题的，因为我是从finder拖过去的

**Comment by rover12421** [comment]
看看是不是有前后看白符的问题.
我更新了代码,你可以再同步测试下.
5f224d9798a9fcb1a2653fc934d445c1e5d98b56

**Comment by zhangciwu** [comment]
的确是空格的原因…… orz
多谢了
