### ISSUE TITLE
Key is invalid for CLion 1.0.1

### ISSUE THREAD

**Issue by nonkr** [rover12421/JetbrainsPatchKeygen#6]
Key is invalid for CLion 1.0.1
![qq 20150505161714](https://cloud.githubusercontent.com/assets/1668287/7469082/31b1ed4a-f342-11e4-941a-0532ba9e45d6.jpg)
---------------------------------------
Product : Clion
UserName : admin
===== LICENSE BEGIN =====
8069-D51239T
00000FD8LzC1FPWCFy5uBGPD2bqkeq
KMZ5PGbSp8ikoGtFuWcsdaZfJ3tBQP
7BEgMIvzAj4E1g1YrXKsaZHcL6!xiO
===== LICENSE END =====

**Comment by unixc3t** [comment]
1.01的验证码失效了。我这也遇到了
